#!/bin/bash

echo -e "\033[33mcleaning up river2D builds...\033[0m"

if [[ -d ./bin/ ]]
then
    rm ./bin/ -rf
fi

for file in *.o
do
    if [[ ! -f $file ]]
    then
        continue;
    fi

    rm $file
done

echo -e "\033[32mcleaned imgsurf!\n\033[0m"
