#!/bin/bash

if [[ ! -d "./bin/" ]]
then
    mkdir ./bin/
fi

if [[ $1 = "" ]]
then
    build="release"
else
    build=$1
fi

args_always="-DBUILD_LINUX \
-Iinclude/ \
-I/usr/include/ \
-Ivendor/imgsurf/include/ \
-Ivendor/imgsurf/vendor/puddle/include/ \
./vendor/imgsurf/vendor/puddle/src/string_view.c \
./vendor/imgsurf/vendor/puddle/src/linux_pd_path.c \
-Wextra -Wall -Wpedantic -Wconversion -Wshadow -Wsign-compare -Wtype-limits -Wunused
-fPIC"

args_common="src/river2Dcommon_main.c \
src/linux_river2Dcommon.c \
src/river2D_util.c \
-c"

args_software="src/linux_river2Dsoftware.c \
-Lbin/$build/ \
-lriver2Dcommon \
-shared \
-fuse-ld=mold"

args_release="-O2"

args_debug="-DDEBUG -g -O0"

args_asan="$args_debug -DASAN \
-fsanitize=address,leak,undefined \
-fno-omit-frame-pointer \
-static-libasan \
-O0"

function compile()
{
    echo "identifying a compiler..."

    clang --version > /dev/null
    if [[ $? = 0 ]]
    then
        echo "found clang."
        compiler="clang"
    else
        gcc --version > /dev/null
        if [[ $? = 0 ]]
        then
            compiler="gcc"
        else
            echo -e "\033[31m\nERROR: no suitable compiler found.\n\033[0m"
        fi
    fi

    if [[ ! -d ./bin/$build ]]
    then
        mkdir ./bin/$build
    fi

    echo ""
    echo -e "\033[36mcompiling river2Dcommon...\033[0m"
    echo ""
    echo "compiling $build build with the following command:"
    echo "$compiler $1 $args_common"

    $($compiler $1 $args_common)
    if [[ $? != 0 ]]
    then
        echo -e "\033[31m\nERROR: $compiler failed to compile river2Dcommon.\n\033[0m"
        exit -1
    fi

    echo ""
    echo -e "\033[36mcreating static libary libriver2Dcommon.a...\033[0m"
    echo ""
    ar rcs ./bin/$build/libriver2Dcommon.a river2D_util.o string_view.o \
    river2Dcommon_main.o linux_river2Dcommon.o linux_pd_path.o

    echo ""
    echo -e "\033[36mcompiling river2Dsoftware...\033[0m"
    echo ""
    echo "compiling $build build with the following command:"
    echo "$compiler $1 $args_software"

    $($compiler $1 $args_software)
    if [[ $? != 0 ]]
    then
        echo -e "\033[31m\nERROR: $compiler failed to compile river2Dsoftware.\n\033[0m"
        exit -1
    fi
    mv ./a.out ./bin/$build/libriver2Dsoftware.so
}

if [[ $build = "release" ]]
then
    compile "$args_always $args_release"
else
if [[ $build = "debug" ]]
then
    compile "$args_always $args_debug"
else
if [[ $build = "asan" ]]
then
    compile "$args_always $args_asan"
else
    echo -e "\033[31m\nERROR: invalid make config: $build.\033[0m"
    exit 3;
fi
fi
fi

echo -e "\n"
