#!/bin/bash

if [[ ! -d "./obj/" ]]
then
    mkdir ./obj/
fi

if [[ ! -d "./build/" ]]
then
    mkdir ./build/
fi

if [[ ! -d "./bin/" ]]
then
    mkdir ./bin/
fi

compile_imgsurf()
{
    if [[ -f "./vendor/imgsurf/run" ]]
    then
        pushd ./vendor/imgsurf/
        ./run $1 --compile-only
        popd
    else
        echo -e "\033[31mERROR: can't find imgsurf's run script.\033[0m"
    fi
}

if [[ $? != 0 ]]
then
    exit -1
fi

compilemsg()
{
    echo ""
    echo -e "\033[36mcompiling river2D...\033[0m"
    echo ""
}

premake5 ecc
premake5 gmake

if [[ $1 = "debug" ]]
then
    compile_imgsurf $1
    compilemsg
    pushd ./build/
    make config=debug_linux
elif [[ $1 = "release" ]]
then
    compile_imgsurf $1
    compilemsg
    pushd ./build/
    make config=release_linux
elif [[ $1 = "asan" ]]
then
    compile_imgsurf $1
    compilemsg
    pushd ./build/
    make config=asan_linux
else
    echo -e "\033[31m\nERROR: invalid make config: $1.\033[0m"
    exit -2;
fi

if [[ $2 = "--compile-only" ]]
then
    exit 0
fi

popd

chmod +x ./bin/release/river2Dmapedit
./bin/release/river2Dmapedit
